name: Deploy to InfinityFree

on:
  push:
    branches:
      - main  # EÄŸer ana branch'in master ise 'main' yerine 'master' yaz

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: ${{ secrets.FTP_PATH }}/
          local-dir: ./        # deploy edilecek local dizin
          cleanRemote: false
          exclude: |
            src/uploads/**
            src/uploads/answers/**
            src/uploads/homeworks/**
            src/config/db.php
            results/**
          dry-run: false
